### ISSUE TITLE
Not worknig in latest Atom

### ISSUE THREAD

**Issue by fornellas** [dsandstrom/atom-ruby-block-converter#14]
Since I upgraded to Atom 1.7.3, the block conversion is not working anymore. It used to work with my previous version (1.6.x I guess).

**Comment by dsandstrom** [comment]
It's working for me.  Can you provide an example of what's not working?

**Comment by fornellas** [comment]
Weird, here at home it is working... It seems that at work I have some "special" combination of factors. Monday I'll check that out.

**Comment by dsandstrom** [comment]
Thanks for following up.  Let me know if you find the cause or I can help more.
